# Generated by Django 5.0.6 on 2024-07-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0002_alter_review_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fueltype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='description',
        ),
    ]
