# Generated by Django 5.0.6 on 2024-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0002_alter_user_address_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
