# Generated by Django 5.0.6 on 2024-06-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0003_alter_transmission_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='rentalstatus',
            options={'verbose_name_plural': 'Rental Statuses'},
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.transmission'),
        ),
    ]
