# Generated by Django 5.0.6 on 2024-07-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0003_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to='car_rental_app.carimage'),
        ),
    ]
