# Generated by Django 5.0.6 on 2024-06-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0004_alter_category_options_alter_rentalstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seating_capacity',
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.category'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='seating_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('engine', models.FloatField()),
                ('horsepower', models.IntegerField()),
                ('year', models.IntegerField()),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.carmodel')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.transmission')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.fueltype')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_rental_app.carvariant'),
        ),
    ]
