# Generated by Django 5.0.6 on 2024-07-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0004_alter_car_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='availability',
        ),
    ]
