# Generated by Django 5.0.6 on 2024-06-29 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0005_fueltype_remove_car_category_remove_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models', to='car_rental_app.category'),
        ),
        migrations.AlterField(
            model_name='carvariant',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='car_rental_app.carmodel'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='car_rental_app.rental'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='car_rental_app.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_rental_app.car')),
            ],
        ),
    ]
