# Generated by Django 5.0.6 on 2024-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0006_alter_carmodel_category_alter_carvariant_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvariant',
            name='year',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
