# Generated by Django 5.0.6 on 2024-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0007_remove_carvariant_year_carmodel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.AddField(
            model_name='carvariant',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
