# Generated by Django 5.0.6 on 2024-06-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0008_remove_car_mileage_carvariant_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
