# Generated by Django 5.0.6 on 2024-06-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0010_alter_car_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvariant',
            name='engine',
            field=models.IntegerField(),
        ),
    ]
