# Generated by Django 5.0.6 on 2024-06-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0011_alter_carvariant_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='is_main',
        ),
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_image', to='car_rental_app.carimage'),
        ),
    ]
